# Generated by Django 5.1.1 on 2026-03-15 13:52

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_count', models.PositiveIntegerField()),
                ('carbon_tons', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price_per_ton', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=10)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('verification_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_company', models.CharField(max_length=255)),
                ('price_per_ton', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('carbon_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.carbonrecord')),
            ],
        ),
        migrations.CreateModel(
            name='MediaUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('photo', 'Photo')], max_length=16)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='uploaded', max_length=16)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreeDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_count', models.PositiveIntegerField(default=0)),
                ('species_detected', models.JSONField(blank=True, default=list)),
                ('confidence_score', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4)),
                ('forest_density_score', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=4)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detection', to='app.mediaupload')),
            ],
        ),
        migrations.AddField(
            model_name='carbonrecord',
            name='detection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_record', to='app.treedetection'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('researcher', 'Researcher'), ('uploader', 'Uploader'), ('corporate_buyer', 'Corporate Buyer')], default='uploader', max_length=32)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_value', models.CharField(max_length=64, unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified', models.BooleanField(default=True)),
                ('carbon_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='app.carbonrecord')),
            ],
        ),
    ]
